#!/bin/bash

if [ ! -d /proc ]; then
	echo "Error: No proc filesystem not found"
	exit 1
fi

mounts=$(cat /proc/mounts | egrep -v "^none|rootfs|tmpfs|udev|devpts|usbfs" | cut -d ' ' -f 2)

for mount in $mounts; do
	total=$(df $mount | tail -1 | awk '{ print $2 }')
	used=$(df $mount | tail -1 | awk '{ print $3 }')
	free=$(df $mount | tail -1 | awk '{ print $4 }')
	echo "${mount}.total.value $total"
	echo "${mount}.used.value $used"
	echo "${mount}.free.value $free"
done
