#!/bin/bash

if [ -f /usr/bin/lsb_release ]; then
	version="$(/usr/bin/lsb_release -d -s)"
elif [ -f /etc/redhat_version ]; then
	version="$(cat /etc/redhat_version)"
else
	version="Unknown"
fi

echo "os_version.value $version"
